spring:
  application:
    name: authentication-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authentication_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          format_sql: true

    jackson:
      serialization:
        INDENT_OUTPUT: true

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:5t8Y!mK2#pL9xQ@vN7zR$wH3cF6jD1sA8eB4gT9uY2iP}
    expiration: 900000

  refresh-token:
    expiration: 604800000 # 7 días
