spring:
  application:
    name: authentication-service

  profiles:
    active: dev

  jackson:
    serialization:
      INDENT_OUTPUT: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

security:
  refresh-token:
    expiration: 604800000 # 7 días

  sso:
    state-expiration: 5m
    authorization-code-expiration: 5m
    simulated:
      redirect-uri: http://localhost:8080/api/auth/sso/callback
      provider: SIMULATED
      code-prefix: sim-code-

  cors:
    allowed-origins:
      - http://localhost:4200

    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS

    allowed-headers:
      - Authorization
      - Content-Type

    allow-credentials: true

app:
  admin: {}
