spring:
  application:
    name: authentication-service

  profiles:
    active: dev

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080

security:
  refresh-token:
    expiration: 604800000 # 7 días

  cors:
    allowed-origins:
      - http://localhost:4200

    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS

    allowed-headers:
      - Authorization
      - Content-Type

    allow-credentials: true

app:
  admin: {}
