version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: authentication-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - authentication-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d authentication_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: authentication-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@econocom.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

    networks:
      - authentication-network

volumes:
  postgres_data:

networks:
  authentication-network:
    driver: bridge