services:

  authentication-service:

    build:
      dockerfile: Dockerfile.dev

    working_dir: /app

    command: mvn spring-boot:run

    environment:
      SPRING_PROFILES_ACTIVE: dev

    volumes:
      - .:/app
      - ~/.m2:/root/.m2